version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:rw
    depends_on:
      - db

  db:
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    image: node:18
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules/:/app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]

volumes:
  db_data: {}
